version: '3.8'

services:
  frontend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortening-frontend
    ports:
      - "4200:4200"
    environment:
      - API_URL=${API_URL}
    restart: always
