version: '3.8'

services:
  frontend:
    build: .
    container_name: url-shortener-frontend
    ports:
      - "4200:4200"
    environment:
      - BASE_URL=http://localhost:8001
      - HOST_NAME=http://localhost:8001
    volumes:
      - .:/app # Mount local files for live updates
      - /app/node_modules # Prevent overwriting node_modules
    working_dir: /app
    command: [ "npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200" ] # Explicitly bind host & port
    restart: always
